### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by m4wayne** [hjlarry/zhihulive#14]
你好，安装到第3步出错
pipenv install安装错误信息：
`[root@zhihulive zhihulive]# pipenv install
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 696, in main
    _verify_python3_env()
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/_unicodefun.py", line 124, in _verify_python3_env
    ' mitigation steps.' + extra
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.

Additional information: on this system no suitable UTF-8
locales were discovered.  This most likely requires resolving
by reconfiguring the locale system.
`

使用pip install安装错误信息：
`[root@zhihulive zhihulive]# pip3 install -r requirements.txt -i --trusted-host http://pypi.douban.com/simple/
Collecting http://pypi.douban.com/simple/
  Downloading http://pypi.douban.com/simple/ (8.2MB)
    100% |################################| 8.2MB 12.8MB/s 
  Cannot unpack file /tmp/pip-4gnxi_ml-unpack/simple (downloaded from /tmp/pip-g95ahdly-build, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-g95ahdly-build
You are using pip version 9.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`
python版本3.6.7
mysql版本5.7.20
谢谢

**Comment by m4wayne** [comment]
pipenv install安装问题是因为locale的问题，原语言en.UTF-8，改LANG="zh_CN.UTF-8"解决；
pip install安装问题升级pip后又出现新错误：Cannot unpack file …… cannot detect archive format；

无奈使用pipenv install继续安装，提示找不到mysqlclient==1.3.13，换清华的的源安装成功；
然后是安装ffmpeg
centos安装ffmpeg：
`yum -y install ffmpeg ffmpeg-devel
su -c 'yum localinstall --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm'

rpm --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-1.el7.nux.noarch.rpm

yum -y install ffmpeg ffmpeg-devel`

**Comment by m4wayne** [comment]
pip install安装错误：Cannot unpack file …… cannot detect archive format，有知道的欢迎反馈

**Comment by m4wayne** [comment]
之前的操作都是在docker中进行的，一直有各种问题。
最终在换了环境和源：win7+Python 3.6.7+5.7.20，清华的源
另外mysqlclient版本改成了1.4.2，1.3.13一直报缺少头文件
